<a href="https://colab.research.google.com/github/OuardiFatiha/ml_sample_project/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Data Types and Attributes

Numpy's main data type is ndarray.

In [ ]:
# control+m+m to turn a cell into markdown in colab

In [ ]:
# create an ndarray
a1=np.array([1,5,7.5])
a1

array([1. , 5. , 7.5])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2=np.array([[1,2,5],
             [7,9,4]])

a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
            [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [ ]:
a2

array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a1.shape , a2.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

In [ ]:
a1.ndim , a2.ndim , a3.ndim #ndim for number of dimension

(1, 2, 3)

In [ ]:
a1.dtype , a2.dtype , a3.dtype

(dtype('float64'), dtype('int64'), dtype('int64'))

In [ ]:
a1.size , a2.size , a3.size

(3, 6, 18)

In [ ]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
# Create a DataFrame for a NumPy Array
import pandas as pd

df=pd.DataFrame(a2)
df

0  1  2
0  1  2  5
1  7  9  4

## 2.Creating arrays

In [ ]:
sample_array = np.array([1,5,9,3])
sample_array

array([1, 5, 9, 3])

In [ ]:
ones =np.ones((2,3),int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
ones.dtype

dtype('int64')

In [ ]:
type(ones)

numpy.ndarray

In [ ]:
zeros =np.zeros((2,3))

In [ ]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
random_array = np.random.randint(0,10,size=(2,3))
random_array

array([[1, 4, 0],
       [4, 2, 1]])

In [ ]:
random_array.size

6

In [ ]:
random_array.shape

(2, 3)

In [ ]:
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.00960524, 0.8828524 , 0.2902946 , 0.9406788 , 0.0159281 ],
       [0.96260172, 0.46262807, 0.21087847, 0.16058261, 0.96056272],
       [0.88471128, 0.37204978, 0.49708224, 0.38181298, 0.39911377]])

In [ ]:
random_array_2.shape

(3, 5)

In [ ]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.34065741, 0.42401492, 0.91016497],
       [0.41959932, 0.4966997 , 0.43433846],
       [0.97087421, 0.86969568, 0.66348007],
       [0.57820564, 0.51649553, 0.1811319 ],
       [0.79918127, 0.27209335, 0.90588938]])

In [ ]:
# Pseudo_random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(2,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9]])

In [ ]:
random_array_4.shape

(2, 3)

In [ ]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3.Viewing arrays and matrices

In [ ]:
np.unique(random_array_4)

array([0, 3, 5, 7, 9])

In [ ]:
a1[0]

1.0

In [ ]:
a1

array([1. , 5. , 7.5])

In [ ]:
a2[0]

array([1, 2, 5])

In [ ]:
a2

array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [ ]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [ ]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [ ]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4.Manipulating & comparing arrays

### Arithmetic

In [ ]:
a1

array([1. , 5. , 7.5])

In [ ]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [ ]:
a1 + ones

array([2. , 6. , 8.5])

In [ ]:
a1 - ones

array([0. , 4. , 6.5])

In [ ]:
a1 * ones

array([1. , 5. , 7.5])

In [ ]:
a2


array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
a1 * a2

array([[ 1. , 10. , 37.5],
       [ 7. , 45. , 30. ]])

In [ ]:
# Broadcasting two arrays of different shape
a2_1 = a2.reshape(2,3,1)
a2_1 * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 35,  40,  45]],

       [[ 70,  77,  84],
        [117, 126, 135],
        [ 64,  68,  72]]])

In [ ]:
a1 / ones

array([1. , 5. , 7.5])

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 0., 0.],
       [7., 1., 0.]])

In [ ]:
a2 ** 2

array([[ 1,  4, 25],
       [49, 81, 16]])

In [ ]:
np.square(a2)

array([[ 1,  4, 25],
       [49, 81, 16]])

In [ ]:
np.add(a1,ones)

array([2. , 6. , 8.5])

In [ ]:
a1 % 2

array([1. , 1. , 1.5])

In [ ]:
a1 /2

array([0.5 , 2.5 , 3.75])

In [ ]:
np.exp(a1)

array([   2.71828183,  148.4131591 , 1808.04241446])

In [ ]:
np.log(a1)

array([0.        , 1.60943791, 2.01490302])