<a href="https://colab.research.google.com/github/OuardiFatiha/ml_sample_project/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

## Data Types and Attributes

Numpy's main data type is ndarray.

In [ ]:
# control+m+m to turn a cell into markdown in colab

In [ ]:
# create an ndarray
a1=np.array([1,5,7.5])
a1

array([1. , 5. , 7.5])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2=np.array([[1,2,5],
             [7,9,4]])

a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
            [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [ ]:
a2

array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a1.shape , a2.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

In [ ]:
a1.ndim , a2.ndim , a3.ndim #ndim for number of dimension

(1, 2, 3)

In [ ]:
a1.dtype , a2.dtype , a3.dtype

(dtype('float64'), dtype('int64'), dtype('int64'))

In [ ]:
a1.size , a2.size , a3.size

(3, 6, 18)

In [ ]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
# Create a DataFrame for a NumPy Array
import pandas as pd

df=pd.DataFrame(a2)
df

0  1  2
0  1  2  5
1  7  9  4

## 2.Creating arrays

In [ ]:
sample_array = np.array([1,5,9,3])
sample_array

array([1, 5, 9, 3])

In [ ]:
ones =np.ones((2,3),int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
ones.dtype

dtype('int64')

In [ ]:
type(ones)

numpy.ndarray

In [ ]:
zeros =np.zeros((2,3))

In [ ]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
random_array = np.random.randint(0,10,size=(2,3))
random_array

array([[1, 4, 0],
       [4, 2, 1]])

In [ ]:
random_array.size

6

In [ ]:
random_array.shape

(2, 3)

In [ ]:
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.00960524, 0.8828524 , 0.2902946 , 0.9406788 , 0.0159281 ],
       [0.96260172, 0.46262807, 0.21087847, 0.16058261, 0.96056272],
       [0.88471128, 0.37204978, 0.49708224, 0.38181298, 0.39911377]])

In [ ]:
random_array_2.shape

(3, 5)

In [ ]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.34065741, 0.42401492, 0.91016497],
       [0.41959932, 0.4966997 , 0.43433846],
       [0.97087421, 0.86969568, 0.66348007],
       [0.57820564, 0.51649553, 0.1811319 ],
       [0.79918127, 0.27209335, 0.90588938]])

In [ ]:
# Pseudo_random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(2,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9]])

In [ ]:
random_array_4.shape

(2, 3)

In [ ]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3.Viewing arrays and matrices

In [ ]:
np.unique(random_array_4)

array([0, 3, 5, 7, 9])

In [ ]:
a1[0]

1.0

In [ ]:
a1

array([1. , 5. , 7.5])

In [ ]:
a2[0]

array([1, 2, 5])

In [ ]:
a2

array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [ ]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [ ]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [ ]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4.Manipulating & comparing arrays

### Arithmetic

In [ ]:
a1

array([1. , 5. , 7.5])

In [ ]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [ ]:
a1 + ones

array([2. , 6. , 8.5])

In [ ]:
a1 - ones

array([0. , 4. , 6.5])

In [ ]:
a1 * ones

array([1. , 5. , 7.5])

In [ ]:
a2


array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
a1 * a2

array([[ 1. , 10. , 37.5],
       [ 7. , 45. , 30. ]])

In [ ]:
# Broadcasting two arrays of different shape
a2_1 = a2.reshape(2,3,1)
a2_1 * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 35,  40,  45]],

       [[ 70,  77,  84],
        [117, 126, 135],
        [ 64,  68,  72]]])

In [ ]:
a1 / ones

array([1. , 5. , 7.5])

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 0., 0.],
       [7., 1., 0.]])

In [ ]:
a2 ** 2

array([[ 1,  4, 25],
       [49, 81, 16]])

In [ ]:
np.square(a2)

array([[ 1,  4, 25],
       [49, 81, 16]])

In [ ]:
np.add(a1,ones)

array([2. , 6. , 8.5])

In [ ]:
a1 % 2

array([1. , 1. , 1.5])

In [ ]:
a1 /2

array([0.5 , 2.5 , 3.75])

In [ ]:
np.exp(a1)

array([   2.71828183,  148.4131591 , 1808.04241446])

In [ ]:
np.log(a1)

array([0.        , 1.60943791, 2.01490302])

### Aggregation
Performing the same operation on a number of things.



In [ ]:
listy_list = [1, 2, 4, 5]
type(listy_list)
sum(listy_list)

12

In [ ]:
sum(a1)

13.5

In [ ]:
np.sum(a1)

13.5

Use Python's methods on Python datatypes (`sum()`) and NymPy's method on NumPy's arrays (`np.sum()`)

In [ ]:
# Create a massive array
massive_array = np.random.random(10000)
massive_array.size

10000

In [ ]:
massive_array[:10]

array([0.03504593, 0.98858075, 0.18200276, 0.96887217, 0.31544848,
       0.41034462, 0.37862868, 0.30446717, 0.13572986, 0.21641119])

In [ ]:
%timeit sum(massive_array) #Python's sum
%timeit np.sum(massive_array) #NumPy's sum

1000 loops, best of 3: 1.62 ms per loop
The slowest run took 11.25 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.5 µs per loop


In [ ]:
1620 / 7.5

216.0

In [ ]:
np.mean(a2)
np.max(a2)
np.min(a2)
np.std(a2) #Standard Deviation is a measure of how spread out a group of numbers from the mean
np.var(a2) #Variance is a measure of the average degree to which each number is different from the mean

7.5555555555555545

In [ ]:
np.std(a2)

2.748737083745107

In [ ]:
# std = sqrt var
np.std(a2) == np.sqrt(np.var(a2))

True

## Resahping and Transposing

In [ ]:
a2

array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [ ]:
a2*a3

ValueError: ignored

In [ ]:
reshaped = a2.reshape(2,3,1)
reshaped

array([[[1],
        [2],
        [5]],

       [[7],
        [9],
        [4]]])

In [ ]:
reshaped * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 35,  40,  45]],

       [[ 70,  77,  84],
        [117, 126, 135],
        [ 64,  68,  72]]])

In [ ]:
a2.T

array([[1, 7],
       [2, 9],
       [5, 4]])

In [ ]:
a2.T.shape

(3, 2)

In [ ]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3.T.shape

(3, 3, 2)

## Dot poduct

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(3,5))

In [ ]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
mat2

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [ ]:
mat1*mat2

ValueError: ignored

In [ ]:
np.dot(mat1,mat2)

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

In [ ]:
np.dot(mat1,mat2).shape

(5, 5)

## COmparison operators

In [ ]:
a1

array([1. , 5. , 7.5])

In [ ]:
a2

array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
bool_arr = a1 > a2
bool_arr

array([[False,  True,  True],
       [False, False,  True]])

In [ ]:
bool_arr.shape, bool_arr.dtype

((2, 3), dtype('bool'))

In [ ]:
a1 > 5

array([False, False,  True])

In [ ]:
a1 < 5

array([ True, False, False])

In [ ]:
a1 == a2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
np.isfinite(a2)

array([[ True,  True,  True],
       [ True,  True,  True]])

## Sorting Arrays

In [ ]:
a1

array([1. , 5. , 7.5])

In [ ]:
np.sort(a1)

array([1. , 5. , 7.5])

In [ ]:
np.argsort(a1)

array([0, 1, 2])

In [ ]:
a2

array([[1, 2, 5],
       [7, 9, 4]])

In [ ]:
np.sort(a2)

array([[1, 2, 5],
       [4, 7, 9]])

In [ ]:
np.argsort(a2)

array([[0, 1, 2],
       [2, 0, 1]])

In [ ]:
np.argmin(a2, axis=0)

array([0, 0, 1])

In [ ]:
np.argmax(a2, axis=1)

array([2, 1])

## Practical Examples

<img src="https://resize-europe1.lanmedia.fr/r/622,311,forcex,center-middle/img/var/europe1/storage/images/europe1/international/le-panda-geant-nest-plus-en-danger-mais-reste-menace-2837755/28733065-1-fre-FR/Le-panda-geant-n-est-plus-en-danger-mais-reste-menace.jpg" />

In [ ]:
## Turn an image to a NumPy Array

from matplotlib.image import imread # imread === image read
panda = imread("https://png.pngtree.com/png-vector/20201126/ourmid/pngtree-christmas-corner-decoration-with-png-image_2482970.jpg")

ValueError: ignored

### Distributions
With np.random.uniform we can draw pseudo-random real numbers from a uniform distribution.

In [2]:
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=-3.4, high=5.9,
                             size=(2, 2))))

0.02071713399890196
0.2693660583665387
array([0.54841584, 0.32804393, 0.01508149])
array([[-2.93536666, -1.46617341],
       [ 2.83616646,  4.680304  ]])


we can use np.random.uniform to draw pseudo-random real numbers from a uniform distribution.

In [4]:
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0,
                            size=(2, 2))))

-0.4050029871128007
6.51606403618199
array([[ 1.90920085, -8.66761499],
       [-5.28974991, -0.20538494]])


The loc and scale keyword arguments represent the mean and standard deviation, respectively

### Custom sampling 
we can also sample from a custom distribution with the np.random.choice function.

In [5]:
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2),
                            p=[0.8, 0.19, 0.01]))) # p keyword is for probabilities when it s not specified they are equal for each element and they sum up to 1 all the time

blue
array(['blue', 'blue'], dtype='<U5')
array([['red', 'red'],
       ['red', 'red']], dtype='<U5')


In [2]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))
# Negated from the previous step
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


Something to note is that np.nan can't be used with any relation operation. Instead, we use np.isnan to filter for the location of np.nan.

In [3]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


### Filtering in NumPy
The np.where function takes in a required first argument, which is a boolean array where True represents the locations of the elements we want to filter for. When the function is applied with only the first argument, it returns a tuple of 1-D arrays.

In [4]:
print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

(array([0, 2]),)
(array([1, 3]),)
array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])


The interesting thing about np.where is that it must be applied with exactly 1 or 3 arguments. When we use 3 arguments, the first argument is still the boolean array. However, the next two arguments represent the True replacement values and the False replacement values, respectively. The output of the function now becomes an array with the same shape as the first argument.

In [5]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-2, -5], [-1, -8]])
print(repr(np.where(np_filter, positives, negatives)))

np_filter = positives > 2
print(repr(np.where(np_filter, positives, negatives)))

np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))

array([[ 1, -5],
       [-1,  4]])
array([[-2, -5],
       [ 3,  4]])
array([[-2, -5],
       [-1, -8]])


In [6]:
# if we wanted to use a constant replacement value, e.g. -1, we could incorporate broadcasting.
print(repr(np.where(np_filter, positives, -1)))

array([[-1, -1],
       [-1, -1]])


### Axis-wise filtering

The np.any function is equivalent to performing a logical OR (||), while the np.all function is equivalent to a logical AND (&&) 

In [4]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(np.any(arr > 0))
print(np.all(arr > 0))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
True
False


In addition to regular sums, NumPy can perform cumulative sums using np.cumsum

In [6]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis=0)))
print(repr(np.cumsum(arr, axis=1)))

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


In [7]:
#  Concatenation
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])
print(repr(np.concatenate([arr1, arr2])))
print(repr(np.concatenate([arr1, arr2], axis=1)))
print(repr(np.concatenate([arr2, arr1], axis=1)))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])


# Saving into a file



In [10]:
arr = np.array([1, 2, 3])
# Saves to 'arr.npy'
np.save('arr.npy', arr)
# Also saves to 'arr.npy'
np.save('arr', arr)

In [13]:
arr =np.load('arr.npy')

arr

array([1, 2, 3])